- name: Setup API instance
  hosts: api
  become: true
  tasks:
    - name: Update APT and install dependencies
      apt:
        update_cache: yes
        name:
          - python3-pip
          - docker.io
          - git
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Clone project repository
      git:
        repo: "https://github.com/koutamMoulaye/devops_mlops_price"
        dest: /home/ubuntu/mlops-devops-prix
        version: main

    - name: Build Docker image
      command: docker build -f docker/api.Dockerfile -t houseprice-api .
      args:
        chdir: /home/ubuntu/mlops-devops-prix

    - name: Run Docker container
      command: docker run -d -p 5001:5001 --name api houseprice-api
      args:
        chdir: /home/ubuntu/mlops-devops-prix
