- name: Setup ML Training instance
  hosts: training
  become: true

  tasks:
    - name: Update APT and install system dependencies
      apt:
        update_cache: yes
        name:
          - python3-pip
          - python3-venv  
          - git
        state: present

    - name: Clone project repository
      git:
        repo: "https://github.com/koutamMoulaye/devops_mlops_price"
        dest: /home/ubuntu/mlops-devops-prix
        version: main
        force: true

    - name: Create Python virtual environment
      command: python3 -m venv /home/ubuntu/venv
      args:
        creates: /home/ubuntu/venv/bin/activate

    - name: Upgrade pip in virtualenv
      command: /home/ubuntu/venv/bin/pip install --upgrade pip

    - name: Install Python requirements in virtualenv
      command: /home/ubuntu/venv/bin/pip install -r /home/ubuntu/mlops-devops-prix/requirements.txt

    - name: Install extra pip packages for MLflow in virtualenv
      command: /home/ubuntu/venv/bin/pip install mlflow[extras] protobuf packaging

    - name: Create mlruns directory
      file:
        path: /home/ubuntu/mlops-devops-prix/mlruns
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Create model directory if not exists
      file:
        path: /home/ubuntu/mlops-devops-prix/model
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Run training script inside virtualenv
      become_user: ubuntu
      command: /home/ubuntu/venv/bin/python /home/ubuntu/mlops-devops-prix/src/training/train_model.py
 